site_name: sdm
theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Examples:
      - "Plot BBox": examples/plot_bbox.ipynb
  - API Reference: reference.md