site_name: sdm
theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature: true
            show_root_heading: true
            show_root_full_path: true
            
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Examples:
      - "Plot BBox": examples/simple_bbox.ipynb
  - API Reference: reference.md